### ISSUE TITLE
Thoughts on Threading

### ISSUE THREAD

**Issue by microlith57** [XXIIVV/Parade#1]
- How can we implement a single threaded OS that is also networked?
  - Would we not have to separate into a client and server, with the client containing an integrated server?
  - How would a single-threaded process receive/send requests?

**Comment by neauoire** [comment]
Yes I think the client should contact the server, a networked query would not be different from a local client query to that same server. If two requests are made at once, then one would wait for the other to complete.

**Comment by microlith57** [comment]
In this case, a Paradise instance should consist of two parts - the part that executes requests, and a queue to store pending request objects. Most simple web servers have this functionality so it should be relatively easy to build into an OS.

**Comment by microlith57** [comment]
I am working on a small implementation of a Parade server in Ruby. It should be on Github soonish! It will probably use my [`ruby_wildcard_lisp`](https://github.com/microlith57/ruby_wildcard_lisp) project.

**Comment by microlith57** [comment]
Update: If my implementation does not fit specifications, I will migrate this issue onto my repository.
